FROM node:16.17.0 
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./todayCheckFE/package.json /app/package.json

RUN npm install -g
RUN npm install -save react-scripts
# RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
COPY ./todayCheckFE ./

CMD ["npm", "start"]